import json
import shutil
from pathlib import Path

for locale in Path("src/lib/assets/locales").glob("*.json"):
    print(f"Updating {locale}...")
    with open(locale) as f:
        old_data = json.load(f)

    with open(Path("tmp") / locale.name) as f:
        new_data = json.load(f)
        old_data.update(new_data)

    with open(locale, "w", encoding="utf8") as f:
        json.dump(old_data, f, ensure_ascii=False, indent=4)

# Clean up the temporary locales generated by SULFUR-toolkit
shutil.rmtree('tmp')

print("Done")